# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'ZZLKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks

  # Pods for ZZLKitDemo
  pod 'YYKit', '~> 1.0.9'
  
end
